name: MERN CI

on:
  push:
    branches: [dev, test, prod]
  pull_request:
    branches: [dev, test, prod]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install & test backend
        working-directory: ./src/backend
        run: |
          npm install
          npm test || echo "No backend tests"

      - name: Install & build frontend
        working-directory: ./src/frontend
        run: |
          npm install
          npm run build